name: Update PUSH

on:
  push:
  schedule:
    - cron: "*/20 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start PUSH
      run: |-
        git diff
        git config --global user.email "buywithcrypto@yandex.com"
        git config --global user.name "bwcblockchain"
        git add --all
        git commit -m "New push" || exit 0
        git push
